version: '2'

services:

    java:
        container_name: openjdk
        image: openjdk:alpine
        depends_on:
        - db
        volumes:
         - ./java:/java
        working_dir: /java
        command: java -version
        depends_on:
         - db
    
    web:
        container_name: nginx
        image: nginx:latest
        volumes:
            - ./code:/code:ro
            - ./site.conf:/etc/nginx/conf.d/default.conf:z
        ports:
             - "8080:80"
             - "443:443"
        links:
             - php
     
     
    php:
        container_name: php
        image: php:fpm
        command: "docker-php-ext-install mysqli"
        volumes:
            - ./code:/code
          #- ./web/:/var/www/html/
          #- ./php:/usr/local/etc/php/php
        restart: always


    db:
        container_name: mariadb
        image: mariadb
        volumes:
            - ./sql_tables.sql://docker-entrypoint-initdb.d/1-sql_tables.sql

        restart: always
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: user
            MYSQL_DATABASE: db
        ports:
            - "3306:3306"
        expose:
            - "3306"

