select * from user_tables;
select count(*) from costumer;
select count(*) from rent;
select count(*) from reservation;
select count(*) from are_friends;
select count(*) from billing;
select count(*) from car;
select count(*) from insurance;
select count(*) from locations;
