version: "3.3"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mongo
    networks:
      - frontend
      - backend
    ports:
      - "8001:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
  db:
    image: mysql:5.6
    command: --init-file /init.sql
    volumes:
        - ./init.sql:/init.sql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: imse
      MYSQL_DATABASE: crmtool
      MYSQL_USER: thomasr97
      MYSQL_PASSWORD: imse
    container_name: imse3
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: imse
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: imse
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
    data:
